fix

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -148,7 +148,6 @@ test-playwright:
         - test-prepare
 
     variables:
-        JOB_TYPE: docker
         CONFIG_ARGS: "-d"
 
     before_script:
@@ -158,26 +157,41 @@ test-playwright:
         - >
             docker ps --filter "label=job=${CI_JOB_NAME}" | grep hours |
             cut -d " " -f1 | while read id; do docker stop -t 5 $id; done || true
-        - export CONTAINER_NAME="test-playwright-${JOB_TYPE}-${CI_JOB_ID}"
-        - >
-            docker run --rm --detach=true --tty=true --name ${CONTAINER_NAME}
-            --label job=${CI_JOB_NAME} ${CI_REGISTRY_IMAGE}:${TAG}
-            ./flask/src/app.py ${CONFIG_ARGS}
 
-        - TARGET_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${CONTAINER_NAME})
-        - 'echo "Target: ${TARGET_IP}"'
+        - >
+            docker run --rm --detach=true --tty=true
+            --name ${CI_JOB_NAME}-${CI_JOB_ID} --label job=${CI_JOB_NAME}
+            --publish :5000
+            ${CI_REGISTRY_IMAGE}:${TAG} ./flask/src/app.py ${CONFIG_ARGS}
+            
+        - >
+            APP_PORT=$(docker port "${CI_JOB_NAME}-${CI_JOB_ID}" 5000 | cut -d: -f2)
+        - >
+            DOCKER_GATEWAY=$(docker network inspect bridge --format="{{range .IPAM.Config}}{{.Gateway}}{{end}}")
+        - >
+            APP_URL="http://${DOCKER_GATEWAY}:${APP_PORT}/rasp-shutter/"
+        - >
+            echo "APP_URL: ${APP_URL}"
+        - >
+            timeout 60 bash -c "until curl --fail --connect-timeout 10 --max-time 15 \"${APP_URL}\" > /dev/null 2>&1;
+            do echo 'Retrying in 5 seconds...'; sleep 5; done" || ACCESS_FAILED=1
+        - |
+            if [ "$ACCESS_FAILED" = "1" ]; then
+                echo "Failed to access App"
+                docker logs ${CI_JOB_NAME}-${CI_JOB_ID} > flask_log.txt
+                docker stop ${CI_JOB_NAME}-${CI_JOB_ID}
+                exit 1
+            fi
 
         - uv run playwright install --with-deps chromium
-
-        - docker logs ${CONTAINER_NAME} > flask_log_1.txt
 
         - >
             uv run pytest --tracing on --output tests/evidence/playwright
             --junit-xml=tests/evidence/playwright-docker-junit.xml
             tests/test_playwright.py --host ${TARGET_IP}
 
-        - docker logs ${CONTAINER_NAME} > flask_log_2.txt
-        - docker stop ${CONTAINER_NAME}
+        - docker logs ${CI_JOB_NAME}-${CI_JOB_ID} > flask_log.txt
+        - docker stop ${CI_JOB_NAME}-${CI_JOB_ID}
 
     artifacts:
         when: always
